routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'admin.'], function () {

  // Set Language For Admin 
  Route::get('/lang/{lang}', 'AuthController@SetLanguage');

  // guest routes for admin 
  Route::group(['middleware' => ['guest:admin']], function () {
    Route::get('login', 'AuthController@showLoginForm')->name('show.login')->middleware('guest:admin');
    Route::post('login', 'AuthController@login')->name('login');
  });


  
  Route::get('logout', 'AuthController@logout')->name('logout');
  
  Route::group(['middleware' => ['admin']], function () {

    /*------------ start Of profile----------*/
      Route::get('profile', [
        'uses'  => 'HomeController@profile',
        'as'    => 'profile.profile',
        'title' => 'profile',
      ]);

      Route::put('profile-update', [
        'uses'  => 'HomeController@updateProfile',
        'as'    => 'profile.update',
        'title' => 'update_profile',
      ]);
      Route::put('profile-update-password', [
        'uses'  => 'HomeController@updatePassword',
        'as'    => 'profile.update_password',
        'title' => 'update_password',
      ]);
    /*------------ end Of profile----------*/

    /*------------ start Of Dashboard----------*/
      Route::get('dashboard', [
        'uses'      => 'HomeController@dashboard',
        'as'        => 'dashboard',
        'icon'      => '<i class="feather icon-home"></i>',
        'title'     => 'main_page',
        'has_sub_route' => false,
        'type'      => 'parent',
      ]);
    /*------------ end Of dashboard ----------*/

    /*------------ start Of intro site  ----------*/
      Route::get('intro-site', [
        'icon'      => '<i class="feather icon-map"></i>',
        'title'     => 'introductory_site',
        'type'      => 'parent',
        'has_sub_route' => true,
        'child'     => [
          'intro_settings.index', 'introsliders.show', 'introsliders.index', 'introsliders.store', 'introsliders.update', 'introsliders.delete', 'introsliders.deleteAll', 'introsliders.create', 'introsliders.edit',
          'introservices.show', 'introservices.index', 'introservices.create', 'introservices.store', 'introservices.edit', 'introservices.update', 'introservices.delete', 'introservices.deleteAll',
          'introparteners.create', 'introparteners.show', 'introparteners.index', 'introparteners.store', 'introparteners.update', 'introparteners.delete', 'introparteners.deleteAll',
          'introsocials.show', 'introsocials.index', 'introsocials.store', 'introsocials.update', 'introsocials.delete', 'introsocials.deleteAll', 'introsocials.edit', 'introsocials.create',
          'introparteners.edit',
        ],
      ]);

      Route::get('intro-settings', [
        'uses'      => 'IntroSetting@index',
        'as'        => 'intro_settings.index',
        'title'     => 'introductory_site_setting',
        'sub_link'  => true ,
      ]);

      /*------------ start Of introsliders ----------*/
          Route::get('introsliders', [
            'uses'      => 'IntroSliderController@index',
            'as'        => 'introsliders.index',
            'title'     => 'intro_slider.index',
            'sub_link'  => true ,
          ]);

          # socials store
          Route::get('introsliders/create', [
            'uses'  => 'IntroSliderController@create',
            'as'    => 'introsliders.create',
            'title' => 'intro_slider.create_page',
          ]);

          # introsliders store
          Route::post('introsliders/store', [
            'uses'  => 'IntroSliderController@store',
            'as'    => 'introsliders.store',
            'title' => 'intro_slider.create',
          ]);

          # socials update
          Route::get('introsliders/{id}/edit', [
            'uses'  => 'IntroSliderController@edit',
            'as'    => 'introsliders.edit',
            'title' => 'intro_slider.edit_page',
          ]);

          # introsliders update
          Route::put('introsliders/{id}', [
            'uses'  => 'IntroSliderController@update',
            'as'    => 'introsliders.update',
            'title' => 'intro_slider.edit',
          ]);

          # introsliders update
          Route::get('introsliders/{id}/Show', [
            'uses'  => 'IntroSliderController@show',
            'as'    => 'introsliders.show',
            'title' => 'intro_slider.show',
          ]);

          # introsliders delete
          Route::delete('introsliders/{id}', [
            'uses'  => 'IntroSliderController@destroy',
            'as'    => 'introsliders.delete',
            'title' => 'intro_slider.delete',
          ]);

          #delete all introsliders
          Route::post('delete-all-introsliders', [
            'uses'  => 'IntroSliderController@destroyAll',
            'as'    => 'introsliders.deleteAll',
            'title' => 'intro_slider.delete_all',
          ]);
      /*------------ end Of introsliders ----------*/

      /*------------ start Of introservices ----------*/
        Route::get('introservices', [
          'uses'  => 'IntroServiceController@index',
          'as'    => 'introservices.index',
          'title' => 'our_services.index',
          'sub_link'  => true ,
        ]);
        # introservices update
        Route::get('introservices/{id}/Show', [
          'uses'  => 'IntroServiceController@show',
          'as'    => 'introservices.show',
          'title' => 'our_services.show',
        ]);
        # socials store
        Route::get('introservices/create', [
          'uses'  => 'IntroServiceController@create',
          'as'    => 'introservices.create',
          'title' => 'our_services.create_page',
        ]);
        # introservices store
        Route::post('introservices/store', [
          'uses'  => 'IntroServiceController@store',
          'as'    => 'introservices.store',
          'title' => 'our_services.create',
        ]);

        # socials update
        Route::get('introservices/{id}/edit', [
          'uses'  => 'IntroServiceController@edit',
          'as'    => 'introservices.edit',
          'title' => 'our_services.edit_page',
        ]);

        # introservices update
        Route::put('introservices/{id}', [
          'uses'  => 'IntroServiceController@update',
          'as'    => 'introservices.update',
          'title' => 'our_services.edit',
        ]);

        # introservices delete
        Route::delete('introservices/{id}', [
          'uses'  => 'IntroServiceController@destroy',
          'as'    => 'introservices.delete',
          'title' => 'our_services.delete',
        ]);

        #delete all introservices
        Route::post('delete-all-introservices', [
          'uses'  => 'IntroServiceController@destroyAll',
          'as'    => 'introservices.deleteAll',
          'title' => 'our_services.delete_all',
        ]);
      /*------------ end Of introservices ----------*/

      /*------------ start Of introparteners ----------*/
        Route::get('introparteners', [
          'uses'  => 'IntroPartenerController@index',
          'as'    => 'introparteners.index',
          'title' => 'success_Partners.index',
          'sub_link'  => true ,
        ]);

        # introparteners update
        Route::get('introparteners/{id}/Show', [
          'uses'  => 'IntroPartenerController@show',
          'as'    => 'introparteners.show',
          'title' => 'success_Partners.show',
        ]);

        # socials store
        Route::get('introparteners/create', [
          'uses'  => 'IntroPartenerController@create',
          'as'    => 'introparteners.create',
          'title' => 'success_Partners.create_page',
        ]);

        # introparteners store
        Route::post('introparteners/store', [
          'uses'  => 'IntroPartenerController@store',
          'as'    => 'introparteners.store',
          'title' => 'success_Partners.create',
        ]);

        # introparteners update
        Route::get('introparteners/{id}/edit', [
          'uses'  => 'IntroPartenerController@edit',
          'as'    => 'introparteners.edit',
          'title' => 'success_Partners.edit_page',
        ]);

        # introparteners update
        Route::put('introparteners/{id}', [
          'uses'  => 'IntroPartenerController@update',
          'as'    => 'introparteners.update',
          'title' => 'success_Partners.edit',
        ]);

        # introparteners delete
        Route::delete('introparteners/{id}', [
          'uses'  => 'IntroPartenerController@destroy',
          'as'    => 'introparteners.delete',
          'title' => 'success_Partners.delete',
        ]);

        #delete all introparteners
        Route::post('delete-all-introparteners', [
          'uses'  => 'IntroPartenerController@destroyAll',
          'as'    => 'introparteners.deleteAll',
          'title' => 'success_Partners.delete_all',
        ]);
      /*------------ end Of introparteners ----------*/

      /*------------ start Of introsocials ----------*/
        Route::get('introsocials', [
          'uses'  => 'IntroSocialController@index',
          'as'    => 'introsocials.index',
          'title' => 'socials.index',
          'sub_link'  => true ,
        ]);

        # introsocials update
        Route::get('introsocials/{id}/Show', [
          'uses'  => 'IntroSocialController@show',
          'as'    => 'introsocials.show',
          'title' => 'socials.show',
        ]);
        # introsocials store
        Route::get('introsocials/create', [
          'uses'  => 'IntroSocialController@create',
          'as'    => 'introsocials.create',
          'title' => 'socials.create_page',
        ]);

        # introsocials store
        Route::post('introsocials/store', [
          'uses'  => 'IntroSocialController@store',
          'as'    => 'introsocials.store',
          'title' => 'socials.create',
        ]);
        # introsocials update
        Route::get('introsocials/{id}/edit', [

app/Models/IntroPartener.php
<?php

namespace App\Models;

class IntroPartener extends BaseModel
{
    protected $fillable = ['image'];
    const IMAGEPATH = 'parteners' ; 
}

app/Http/Controllers/Admin/IntroPartenerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Traits\ReportTrait;
use Illuminate\Http\Request;
use App\Models\IntroPartener;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\IntroParteners\Store;
use App\Http\Requests\Admin\IntroParteners\Update;

class IntroPartenerController extends Controller
{
    public function index()
    {
        if (request()->ajax()) {
            $partensers = IntroPartener::search(request()->searchArray)->paginate(30);
            $html = view('admin.introparteners.table' ,compact('partensers'))->render() ;
            return response()->json(['html' => $html]);
        }
        return view('admin.introparteners.index');
    }

    public function create()
    {
        return view('admin.introparteners.create');
    }


    public function store(Store $request)
    {
        IntroPartener::create($request->validated());
        ReportTrait::addToLog('  اضافه شريك لقسم شركائنا في العمل') ;
        return response()->json(['url' => route('admin.introparteners.index')]);
    }
    public function edit($id)
    {
        $partenser = IntroPartener::findOrFail($id);
        return view('admin.introparteners.edit' , ['partenser' => $partenser]);
    }

    public function update(Update $request, $id)
    {
        IntroPartener::findOrFail($id)->update($request->validated());
        ReportTrait::addToLog('  تعديل شريك  في قسم شركائنا في العمل') ;
        return response()->json(['url' => route('admin.introparteners.index')]);
    }
    public function show($id)
    {
        $partenser = IntroPartener::findOrFail($id);
        return view('admin.introparteners.show' , ['partenser' => $partenser]);
    }
    
    public function destroy($id)
    {
        IntroPartener::findOrFail($id)->delete();
        ReportTrait::addToLog('  حذف شريك  من قسم شركائنا في العمل') ;
        return response()->json(['id' =>$id]);
    }

    public function destroyAll(Request $request)
    {
        $requestIds = json_decode($request->data);
        
        foreach ($requestIds as $id) {
            $ids[] = $id->id;
        }
        if (IntroPartener::whereIn('id' , $ids)->get()->each->delete()) {
            ReportTrait::addToLog('  حذف مجموعه من الشركاء  من قسم شركائنا في العمل') ;
            return response()->json('success');
        } else {
            return response()->json('failed');
        }
    }
}

resources/views/admin/introparteners/create.blade.php
@extends('admin.layout.master')
{{-- extra css files --}}
@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('admin/app-assets/vendors/css/extensions/sweetalert2.min.css')}}">
@endsection
{{-- extra css files --}}

@section('content')
<!-- // Basic multiple Column Form section start -->
<section id="multiple-column-form">
    <div class="row match-height">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{{__('admin.add')}}</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form  method="POST" action="{{route('admin.introparteners.store')}}" class="store form-horizontal" novalidate>
                            @csrf
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="imgMontg col-12 text-center">
                                            <div class="dropBox">
                                                <div class="textCenter">
                                                    <div class="imagesUploadBlock">
                                                        <label class="uploadImg">
                                                            <span><i class="feather icon-image"></i></span>
                                                            <input type="file" accept="image/*" name="image" class="imageUploader" required>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-12 d-flex justify-content-center mt-3">
                                        <button type="submit" class="btn btn-primary mr-1 mb-1 submit_button">{{__('admin.add')}}</button>
                                        <a href="{{ url()->previous() }}" type="reset" class="btn btn-outline-warning mr-1 mb-1">{{__('admin.back')}}</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection
@section('js')
    <script src="{{asset('admin/app-assets/vendors/js/extensions/sweetalert2.all.min.js')}}"></script>
    <script src="{{asset('admin/app-assets/js/scripts/extensions/sweet-alerts.js')}}"></script>
    
    {{-- show selected image script --}}
        @include('admin.shared.addImage')
    {{-- show selected image script --}}

    {{-- submit add form script --}}
        @include('admin.shared.submitAddForm')
    {{-- submit add form script --}}
    
@endsection

resources/views/admin/introparteners/edit.blade.php
@extends('admin.layout.master')
{{-- extra css files --}}
@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('admin/app-assets/vendors/css/extensions/sweetalert2.min.css')}}">
@endsection
{{-- extra css files --}}

@section('content')
<!-- // Basic multiple Column Form section start -->
<section id="multiple-column-form">
    <div class="row match-height">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{{__('admin.edit')}}</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form  method="POST" action="{{route('admin.introparteners.update' , ['id' => $partenser->id])}}" class="store form-horizontal" novalidate>
                            @csrf
                            @method('PUT')
                            <div class="form-body">
                                <div class="row">

                                    <div class="col-12">
                                        <div class="imgMontg col-12 text-center">
                                            <div class="dropBox">
                                                <div class="textCenter">
                                                    <div class="imagesUploadBlock">
                                                        <label class="uploadImg">
                                                            <span><i class="feather icon-image"></i></span>
                                                            <input type="file" accept="image/*" name="image" class="imageUploader">
                                                        </label>
                                                        <div class="uploadedBlock">
                                                            <img src="{{$partenser->image}}">
                                                            <button class="close"><i class="feather icon-trash-2"></i></button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-12 d-flex justify-content-center mt-3">
                                        <button type="submit" class="btn btn-primary mr-1 mb-1 submit_button">{{__('admin.update')}}</button>
                                        <a href="{{ url()->previous() }}" type="reset" class="btn btn-outline-warning mr-1 mb-1">{{__('admin.back')}}</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection
@section('js')
    <script src="{{asset('admin/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js')}}"></script>
    <script src="{{asset('admin/app-assets/js/scripts/forms/validation/form-validation.js')}}"></script>
    <script src="{{asset('admin/app-assets/vendors/js/extensions/sweetalert2.all.min.js')}}"></script>
    <script src="{{asset('admin/app-assets/js/scripts/extensions/sweet-alerts.js')}}"></script>
    
   
    {{-- show selected image script --}}
        @include('admin.shared.addImage')
    {{-- show selected image script --}}

    {{-- submit edit form script --}}
        @include('admin.shared.submitEditForm')
    {{-- submit edit form script --}}
    
@endsection

resources/views/admin/introparteners/index.blade.php
@extends('admin.layout.master')

@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('admin/app-assets/vendors/css/extensions/sweetalert2.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('admin/index_page.css')}}">
@endsection

@section('content')
<div class="content-body">

    <div class="mb-1 d-flex justify-content-between m-0">
        <x-admin.buttons 
            addbutton="{{ route('admin.introparteners.create') }}"
            deletebutton="{{ route('admin.introparteners.deleteAll') }}"
        />
    </div>
    <div class="table_content_append">
    </div>
</div>


    
@endsection

@section('js')

    <script src="{{asset('admin/app-assets/vendors/js/extensions/sweetalert2.all.min.js')}}"></script>
    <script src="{{asset('admin/app-assets/js/scripts/extensions/sweet-alerts.js')}}"></script>

    {{-- delete all script --}}
        @include('admin.shared.deleteAll')
    {{-- delete all script --}}

    {{-- delete one user script --}}
        @include('admin.shared.deleteOne')
    {{-- delete one user script --}}

    {{-- delete one user script --}}
        @include('admin.shared.filter_js' , [ 'index_route' => url('admin/introparteners')])
    {{-- delete one user script --}}
@endsection

resources/views/admin/introparteners/show.blade.php
@extends('admin.layout.master')

@section('content')
<!-- // Basic multiple Column Form section start -->
<section id="multiple-column-form">
    <div class="row match-height">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">{{__('admin.show')}}</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form  class="store form-horizontal" >
                            <div class="form-body">
                                <div class="row">
                                    
                                    <div class="col-12">
                                        <div class="imgMontg col-12 text-center">
                                            <div class="dropBox">
                                                <div class="textCenter">
                                                    <div class="imagesUploadBlock">
                                                        <label class="uploadImg">
                                                            <span><i class="feather icon-image"></i></span>
                                                            <input type="file" accept="image/*" name="image" class="imageUploader">
                                                        </label>
                                                        <div class="uploadedBlock">
                                                            <img src="{{$partenser->image}}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-12 d-flex justify-content-center mt-3">
                                        <a href="{{ url()->previous() }}" type="reset" class="btn btn-outline-warning mr-1 mb-1">{{__('admin.back')}}</a>
                                    </div>
                                    
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection

@section('js')
    <script>
        $('.store input').attr('disabled' , true)
        $('.store textarea').attr('disabled' , true)
        $('.store select').attr('disabled' , true)

    </script>
@endsection

resources/views/admin/introparteners/table.blade.php
<div class="position-relative">
    {{-- table loader  --}}
    <div class="table_loader" >
        {{__('admin.loading')}}
    </div>
    {{-- table loader  --}}
    {{-- table content --}}
    <table class="table " id="tab">
        <thead>
            <tr>
                <th>
                    <label class="container-checkbox">
                        <input type="checkbox" value="value1" name="name1" id="checkedAll">
                        <span class="checkmark"></span>
                    </label>
                </th>
                <th>{{__('admin.image')}}</th>
                <th>{{__('admin.control')}}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($partensers as $partenser)
                <tr class="delete_partenser">
                    <td class="text-center">
                        <label class="container-checkbox">
                            <input type="checkbox" class="checkSingle" id="{{$partenser->id}}">
                            <span class="checkmark"></span>
                        </label>
                    </td>
                    <td><img src="{{$partenser->image}}" width="50px" height="50px" alt=""></td>
                    <td class="product-action">
                        <span class="text-primary"><a href="{{route('admin.introparteners.show' , ['id' => $partenser->id])}}"><i class="feather icon-eye"></i></a></span>
                        <span class="action-edit text-primary"><a href="{{route('admin.introparteners.edit' , ['id' => $partenser->id])}}"><i class="feather icon-edit"></i></a></span>
                        <span class="delete-row text-danger" data-url="{{url('admin/introparteners/'.$partenser->id)}}"><i class="feather icon-trash"></i></span>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    {{-- table content --}}
    {{-- no data found div --}}
    @if ($partensers->count() == 0)
    <div class="d-flex flex-column w-100 align-center mt-4">
        <img src="{{asset('/storage/images/no_data.png')}}" width="200px" style="" alt="">
        <span class="mt-2" style="font-family: cairo ;margin-right: 35px">{{__('admin.there_are_no_matches_matching')}}</span>
    </div>
    @endif
    {{-- no data found div --}}

</div>
{{-- pagination  links div --}}
@if ($partensers->count() > 0 && $partensers instanceof \Illuminate\Pagination\AbstractPaginator )
    <div class="d-flex justify-content-center mt-3">
        {{$partensers->links()}}
    </div>
@endif
{{-- pagination  links div --}}