routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['as' => 'admin.'], function () {

  // Set Language For Admin 
  Route::get('/lang/{lang}', 'AuthController@SetLanguage');

  // guest routes for admin 
  Route::group(['middleware' => ['guest:admin']], function () {
    Route::get('login', 'AuthController@showLoginForm')->name('show.login')->middleware('guest:admin');
    Route::post('login', 'AuthController@login')->name('login');
  });


  
  Route::get('logout', 'AuthController@logout')->name('logout');
  
  Route::group(['middleware' => ['admin']], function () {

    /*------------ start Of profile----------*/
      Route::get('profile', [
        'uses'  => 'HomeController@profile',
        'as'    => 'profile.profile',
        'title' => 'profile',
      ]);

      Route::put('profile-update', [
        'uses'  => 'HomeController@updateProfile',
        'as'    => 'profile.update',
        'title' => 'update_profile',
      ]);
      Route::put('profile-update-password', [
        'uses'  => 'HomeController@updatePassword',
        'as'    => 'profile.update_password',
        'title' => 'update_password',
      ]);
    /*------------ end Of profile----------*/

    /*------------ start Of Dashboard----------*/
      Route::get('dashboard', [
        'uses'      => 'HomeController@dashboard',
        'as'        => 'dashboard',
        'icon'      => '<i class="feather icon-home"></i>',
        'title'     => 'main_page',
        'has_sub_route' => false,
        'type'      => 'parent',
      ]);
    /*------------ end Of dashboard ----------*/

    /*------------ start Of intro site  ----------*/
      Route::get('intro-site', [
        'icon'      => '<i class="feather icon-map"></i>',
        'title'     => 'introductory_site',
        'type'      => 'parent',
        'has_sub_route' => true,
        'child'     => [
          'intro_settings.index', 'introsliders.show', 'introsliders.index', 'introsliders.store', 'introsliders.update', 'introsliders.delete', 'introsliders.deleteAll', 'introsliders.create', 'introsliders.edit',
          'introservices.show', 'introservices.index', 'introservices.create', 'introservices.store', 'introservices.edit', 'introservices.update', 'introservices.delete', 'introservices.deleteAll',
          'introparteners.create', 'introparteners.show', 'introparteners.index', 'introparteners.store', 'introparteners.update', 'introparteners.delete', 'introparteners.deleteAll',
          'introsocials.show', 'introsocials.index', 'introsocials.store', 'introsocials.update', 'introsocials.delete', 'introsocials.deleteAll', 'introsocials.edit', 'introsocials.create',
          'introparteners.edit',
        ],
      ]);

      Route::get('intro-settings', [
        'uses'      => 'IntroSetting@index',
        'as'        => 'intro_settings.index',
        'title'     => 'introductory_site_setting',
        'sub_link'  => true ,
      ]);

      /*------------ start Of introsliders ----------*/
          Route::get('introsliders', [
            'uses'      => 'IntroSliderController@index',
            'as'        => 'introsliders.index',
            'title'     => 'intro_slider.index',
            'sub_link'  => true ,
          ]);

          # socials store
          Route::get('introsliders/create', [
            'uses'  => 'IntroSliderController@create',
            'as'    => 'introsliders.create',
            'title' => 'intro_slider.create_page',
          ]);

          # introsliders store
          Route::post('introsliders/store', [
            'uses'  => 'IntroSliderController@store',
            'as'    => 'introsliders.store',
            'title' => 'intro_slider.create',
          ]);

          # socials update
          Route::get('introsliders/{id}/edit', [
            'uses'  => 'IntroSliderController@edit',
            'as'    => 'introsliders.edit',
            'title' => 'intro_slider.edit_page',
          ]);

          # introsliders update
          Route::put('introsliders/{id}', [
            'uses'  => 'IntroSliderController@update',
            'as'    => 'introsliders.update',
            'title' => 'intro_slider.edit',
          ]);

          # introsliders update
          Route::get('introsliders/{id}/Show', [
            'uses'  => 'IntroSliderController@show',
            'as'    => 'introsliders.show',
            'title' => 'intro_slider.show',
          ]);

          # introsliders delete
          Route::delete('introsliders/{id}', [
            'uses'  => 'IntroSliderController@destroy',
            'as'    => 'introsliders.delete',
            'title' => 'intro_slider.delete',
          ]);

          #delete all introsliders
          Route::post('delete-all-introsliders', [
            'uses'  => 'IntroSliderController@destroyAll',
            'as'    => 'introsliders.deleteAll',
            'title' => 'intro_slider.delete_all',
          ]);
      /*------------ end Of introsliders ----------*/

      /*------------ start Of introservices ----------*/
        Route::get('introservices', [
          'uses'  => 'IntroServiceController@index',
          'as'    => 'introservices.index',
          'title' => 'our_services.index',
          'sub_link'  => true ,
        ]);
        # introservices update
        Route::get('introservices/{id}/Show', [
          'uses'  => 'IntroServiceController@show',
          'as'    => 'introservices.show',
          'title' => 'our_services.show',
        ]);
        # socials store
        Route::get('introservices/create', [
          'uses'  => 'IntroServiceController@create',
          'as'    => 'introservices.create',
          'title' => 'our_services.create_page',
        ]);
        # introservices store
        Route::post('introservices/store', [
          'uses'  => 'IntroServiceController@store',
          'as'    => 'introservices.store',
          'title' => 'our_services.create',
        ]);

        # socials update
        Route::get('introservices/{id}/edit', [
          'uses'  => 'IntroServiceController@edit',
          'as'    => 'introservices.edit',
          'title' => 'our_services.edit_page',
        ]);

        # introservices update
        Route::put('introservices/{id}', [
          'uses'  => 'IntroServiceController@update',
          'as'    => 'introservices.update',
          'title' => 'our_services.edit',
        ]);

        # introservices delete
        Route::delete('introservices/{id}', [
          'uses'  => 'IntroServiceController@destroy',
          'as'    => 'introservices.delete',
          'title' => 'our_services.delete',
        ]);

        #delete all introservices
        Route::post('delete-all-introservices', [
          'uses'  => 'IntroServiceController@destroyAll',
          'as'    => 'introservices.deleteAll',
          'title' => 'our_services.delete_all',
        ]);
      /*------------ end Of introservices ----------*/

      /*------------ start Of introparteners ----------*/
        Route::get('introparteners', [
          'uses'  => 'IntroPartenerController@index',
          'as'    => 'introparteners.index',
          'title' => 'success_Partners.index',
          'sub_link'  => true ,
        ]);

        # introparteners update
        Route::get('introparteners/{id}/Show', [
          'uses'  => 'IntroPartenerController@show',
          'as'    => 'introparteners.show',
          'title' => 'success_Partners.show',
        ]);

        # socials store
        Route::get('introparteners/create', [
          'uses'  => 'IntroPartenerController@create',
          'as'    => 'introparteners.create',
          'title' => 'success_Partners.create_page',
        ]);

        # introparteners store
        Route::post('introparteners/store', [
          'uses'  => 'IntroPartenerController@store',
          'as'    => 'introparteners.store',
          'title' => 'success_Partners.create',
        ]);

        # introparteners update
        Route::get('introparteners/{id}/edit', [
          'uses'  => 'IntroPartenerController@edit',
          'as'    => 'introparteners.edit',
          'title' => 'success_Partners.edit_page',
        ]);

        # introparteners update
        Route::put('introparteners/{id}', [
          'uses'  => 'IntroPartenerController@update',
          'as'    => 'introparteners.update',
          'title' => 'success_Partners.edit',
        ]);

        # introparteners delete
        Route::delete('introparteners/{id}', [
          'uses'  => 'IntroPartenerController@destroy',
          'as'    => 'introparteners.delete',
          'title' => 'success_Partners.delete',
        ]);

        #delete all introparteners
        Route::post('delete-all-introparteners', [
          'uses'  => 'IntroPartenerController@destroyAll',
          'as'    => 'introparteners.deleteAll',
          'title' => 'success_Partners.delete_all',
        ]);
      /*------------ end Of introparteners ----------*/

      /*------------ start Of introsocials ----------*/
        Route::get('introsocials', [
          'uses'  => 'IntroSocialController@index',
          'as'    => 'introsocials.index',
          'title' => 'socials.index',
          'sub_link'  => true ,
        ]);

        # introsocials update
        Route::get('introsocials/{id}/Show', [
          'uses'  => 'IntroSocialController@show',
          'as'    => 'introsocials.show',
          'title' => 'socials.show',
        ]);
        # introsocials store
        Route::get('introsocials/create', [
          'uses'  => 'IntroSocialController@create',
          'as'    => 'introsocials.create',
          'title' => 'socials.create_page',
        ]);

        # introsocials store
        Route::post('introsocials/store', [
          'uses'  => 'IntroSocialController@store',
          'as'    => 'introsocials.store',
          'title' => 'socials.create',
        ]);
        # introsocials update
        Route::get('introsocials/{id}/edit', [

resources/views/admin/admins/create.blade.php
@extends('admin.layout.master')
{{-- extra css files --}}
@section('css')
  <link rel="stylesheet" type="text/css"
        href="{{ asset('admin/app-assets/css-rtl/plugins/forms/validation/form-validation.css') }}">
  <link rel="stylesheet" type="text/css"
        href="{{ asset('admin/app-assets/vendors/css/extensions/sweetalert2.min.css') }}">
@endsection
{{-- extra css files --}}

@section('content')
  <!-- // Basic multiple Column Form section start -->
  <section id="multiple-column-form">
    <div class="row match-height">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">{{ __('admin.add') }}</h4>
          </div>
          <div class="card-content">
            <div class="card-body">
              <form method="POST" action="{{ route('admin.admins.store') }}"
                    class="store form-horizontal" novalidate>
                @csrf
                <div class="form-body">
                  <div class="row">
                    <div class="col-12">
                      <div class="imgMontg col-12 text-center">
                        <div class="dropBox">
                          <div class="textCenter">
                            <div class="imagesUploadBlock">
                              <label class="uploadImg">
                                <span><i class="feather icon-image"></i></span>
                                <input type="file" accept="image/*" name="image"
                                       class="imageUploader">
                              </label>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="col-md-6 col-12">
                      <div class="form-group">
                        <label for="first-name-column">{{  __('admin.name') }}</label>
                        <div class="controls">
                          <input type="text" name="name" class="form-control"
                                 placeholder="{{  __('admin.write_the_name') }}" required
                                 data-validation-required-message="{{ __('admin.this_field_is_required') }}">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6 col-12">
                      <div class="form-group">
                        <label for="first-name-column">{{ __('admin.phone_number') }}</label>
                        <div class="controls">
                          <input type="number" name="phone" class="form-control"
                                 placeholder="{{  __('admin.enter_phone_number') }}" required
                                 data-validation-required-message="{{ __('admin.this_field_is_required') }}">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6 col-12">
                      <div class="form-group">
                        <label
                               for="first-name-column">{{ __('admin.email') }}</label>
                        <div class="controls">
                          <input type="email" name="email" class="form-control"
                                 placeholder="{{  __('admin.enter_the_email') }}"
                                 required
                                 data-validation-required-message="{{ __('admin.this_field_is_required') }}"
                                 data-validation-email-message="{{__('admin.email_formula_is_incorrect')}}">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6 col-12">
                      <div class="form-group">
                        <label for="first-name-column">{{ __('admin.password')  }}</label>
                        <div class="controls">
                          <input type="password" name="password" class="form-control"
                                 required
                                 data-validation-required-message="{{ __('admin.this_field_is_required') }}">
                        </div>
                      </div>
                    </div>

                    {{-- <div class="col-md-12 col-12">
                      <div class="form-group">
                        <label for="first-name-column">{{ __('admin.status')}}</label>
                        <div class="controls">
                          <select name="is_blocked" class="select2 form-control" required
                                  data-validation-required-message="{{ __('admin.this_field_is_required') }}">
                            <option value>{{ __('admin.Select_the_blocking_status') }}</option>
                            <option value="1">{{ __('admin.Prohibited') }}</option>
                            <option value="0" selected>{{ __('admin.Unspoken')}}</option>
                          </select>
                        </div>
                      </div>
                    </div> --}}
                    <div class="col-md-12 col-12">
                      <div class="form-group">
                        <label for="first-name-column">{{ __('admin.Validity')}}</label>
                        <div class="controls">
                          <select name="role_id" class="select2 form-control" required
                                  data-validation-required-message="{{ __('admin.this_field_is_required') }}">
                            <option value>{{  __('admin.Select_the_validity') }}</option>
                            @foreach ($roles as $role)
                              <option value="{{ $role->id }}">{{ $role->name }}
                              </option>
                            @endforeach
                          </select>
                        </div>
                      </div>
                    </div>

                    <div class="col-12 d-flex justify-content-center mt-3">
                      <button type="submit"
                              class="btn btn-primary mr-1 mb-1 submit_button">{{ __('admin.add') }}</button>
                      <a href="{{ url()->previous() }}" type="reset"
                         class="btn btn-outline-warning mr-1 mb-1">{{__('admin.back') }}</a>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

@endsection
@section('js')
  <script
          src="{{ asset('admin/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js') }}">
  </script>
  <script
          src="{{ asset('admin/app-assets/js/scripts/forms/validation/form-validation.js') }}">
  </script>
  <script
          src="{{ asset('admin/app-assets/vendors/js/extensions/sweetalert2.all.min.js') }}">
  </script>
  <script src="{{ asset('admin/app-assets/js/scripts/extensions/sweet-alerts.js') }}">
  </script>

  {{-- show selected image script --}}
  @include('admin.shared.addImage')
  {{-- show selected image script --}}

  {{-- submit add form script --}}
  @include('admin.shared.submitAddForm')
  {{-- submit add form script --}}

@endsection

resources/views/admin/admins/index.blade.php
@extends('admin.layout.master')

@section('css')
    <link rel="stylesheet" type="text/css" href="{{asset('admin/app-assets/vendors/css/extensions/sweetalert2.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('admin/index_page.css')}}">
@endsection

@section('content')
    <div class="content-body">
        <div class="mb-1 d-flex justify-content-between m-0">
            <x-admin.buttons 
                addbutton="{{ route('admin.admins.create') }}"
                deletebutton="{{ route('admin.admins.deleteAll') }}"
                extrabuttons="true"
            >
                <x-slot name="extrabuttonsdiv">
                    <a class="btn bg-gradient-info mr-1 mb-1 waves-effect waves-light"  href="{{url(route('admin.master-export', 'Admin'))}}"><i  class="fa fa-file-excel-o"></i>
                        {{ __('admin.export') }}</a>
                </x-slot>
            </x-admin.buttons>

            <x-admin.filter 
                datefilter="true" 
                order="true" 
                :searchArray="[
                    'name' => [
                        'input_type' => 'text' , 
                        'input_name' => __('admin.name'), 
                    ] ,
                    'phone' => [
                        'input_type' => 'text' , 
                        'input_name' => __('admin.phone') , 
                    ] ,
                    'email' => [
                        'input_type' => 'text' , 
                        'input_name' => __('admin.email') , 
                    ] ,
                    
                ]"
            />
        </div>
        <div class="table_content_append">

        </div>
    </div>
@endsection

@section('js')

    <script src="{{asset('admin/app-assets/vendors/js/extensions/sweetalert2.all.min.js')}}"></script>
    <script src="{{asset('admin/app-assets/js/scripts/extensions/sweet-alerts.js')}}"></script>
    @include('admin.shared.deleteAll')
    @include('admin.shared.deleteOne')
    @include('admin.shared.filter_js' , [ 'index_route' => url('admin/admins')])
    <script>
        $(document).ready(function(){
            $(document).on('click','.block_user',function(e){
                e.preventDefault();
                $.ajax({
                    url: '{{url("admin/admins/block")}}',
                    method: 'post',
                    data: { id : $(this).data('id')},
                    dataType:'json',
                    beforeSend: function(){
                        $(this).html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>').attr('disable',true)
                    },
                    success: function(response){
                        Swal.fire({
                                    position: 'top-start',
                                    type: 'success',
                                    title: response.message,
                                    showConfirmButton: false,
                                    timer: 1500,
                                    confirmButtonClass: 'btn btn-primary',
                                    buttonsStyling: false,
                                })
                        setTimeout(function(){
                            window.location.reload()
                        }, 1000);
                    },
                });
    
            });
        });
    </script>
@endsection

resources/views/admin/admins/profile.blade.php
@extends('admin.layout.master')
{{-- extra css files --}}
@section('css')
  <link rel="stylesheet" type="text/css" href="{{ asset('admin/app-assets/css-rtl/plugins/forms/validation/form-validation.css') }}">
@endsection
{{-- extra css files --}}
@section('content')

<div class="content-body">
  <!-- account setting page start -->
  <section id="page-account-settings">
      <div class="row">
          <!-- left menu section -->
          <div class="col-md-3 mb-2 mb-md-0">
              <ul class="nav nav-pills flex-column mt-md-0 mt-1">

                  <li class="nav-item">
                      <a class="nav-link d-flex py-75 active" id="account-pill-main" data-toggle="pill" href="#account-vertical-main" aria-expanded="true">
                          <i class="feather icon-settings mr-50 font-medium-3"></i>
                          {{__('admin.main_data')}}
                      </a>
                  </li>
                  <li class="nav-item" style="margin-top: 3px" > 
                      <a class="nav-link d-flex py-75" id="account-pill-terms" data-toggle="pill" href="#account-vertical-terms" aria-expanded="false">
                          <i class="feather icon-edit-1 mr-50 font-medium-3"></i>
                          {{__('admin.change_password')}}
                      </a>
                  </li>

              </ul>
          </div>
          <!-- right content section -->
          <div class="col-md-9">
              <div class="card">
                  <div class="card-content">
                      <div class="card-body">
                          <div class="tab-content">

                              <div role="tabpanel" class="tab-pane active" id="account-vertical-main" aria-labelledby="account-pill-main" aria-expanded="true">
                                <form action="{{route('admin.profile.update')}}" method="post" enctype="multipart/form-data" class="form-horizontal" novalidate>
                                    @method('put')
                                    @csrf
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="imgMontg  text-center">
                                                <div class="dropBox">
                                                    <div class="textCenter d-flex flex-lg-column">
                                                        <div class="imagesUploadBlock">
                                                            <label class="uploadImg">
                                                                <span><i class="feather icon-image"></i></span>
                                                                <input type="file" accept="image/*" name="image" class="imageUploader">
                                                            </label>
                                                            <div class="uploadedBlock">
                                                                <img src="{{auth('admin')->user()->image}}">
                                                                <button class="close"><i class="feather icon-trash-2"></i></button>
                                                            </div>
                                                        </div>
                                                        <span>{{__('admin.profile_image')}}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="col-md-6 col-12">
                                            <div class="form-group">
                                                <label for="first-name-column">{{  __('admin.name') }}</label>
                                                <div class="controls">
                                                    <input type="text" name="name" class="form-control" value="{{auth('admin')->user()->name}}" placeholder="{{  __('admin.write_the_name') }}" required data-validation-required-message="{{ __('admin.this_field_is_required') }}">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-6 col-12">
                                            <div class="form-group">
                                                <label for="first-name-column">{{ __('admin.phone_number') }}</label>
                                                <div class="controls">
                                                    <input type="number" value="{{auth('admin')->user()->phone}}" name="phone" class="form-control" placeholder="{{  __('admin.enter_phone_number') }}" required data-validation-required-message="{{ __('admin.this_field_is_required') }}">
                                                </div>
                                            </div>
                                        </div>


                                        <div class="col-md-6 col-12">
                                            <div class="form-group">
                                                <label for="first-name-column">{{ __('admin.email') }}</label>
                                                <div class="controls">
                                                <input type="email" value="{{auth('admin')->user()->email}}"  name="email" class="form-control" placeholder="{{  __('admin.enter_the_email') }}" required data-validation-required-message="{{ __('admin.this_field_is_required') }}" data-validation-email-message="{{__('admin.email_formula_is_incorrect')}}">
                                                </div>
                                            </div>
                                        </div>
                                           
                                        
                                        <div class="col-12 d-flex justify-content-center mt-3">
                                            <button type="submit" class="btn btn-primary mr-1 mb-1 submit_button">{{__('admin.saving_changes')}}</button>
                                            <a href="{{ url()->previous() }}" type="reset" class="btn btn-outline-warning mr-1 mb-1">{{__('admin.back')}}</a>
                                        </div>
                                    </div>
                                </form>
                              </div>

                              <div role="tabpanel" class="tab-pane" id="account-vertical-terms" aria-labelledby="account-pill-terms" aria-expanded="false">
                                <form action="{{route('admin.profile.update_password')}}" method="post" enctype="multipart/form-data">
                                    @method('put')
                                    @csrf
                                        <div class="row">

                                            <div class="col-md-4 col-12">
                                                <div class="form-group">
                                                    <label for="first-name-column">{{  __('admin.old_password') }}</label>
                                                    <div class="controls">
                                                        <input type="password" name="old_password" class="form-control"  required data-validation-required-message="{{ __('admin.this_field_is_required') }}">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4 col-12">
                                                <div class="form-group">
                                                    <label for="first-name-column">{{  __('admin.new_password') }}</label>
                                                    <div class="controls">
                                                        <input type="password" name="password" class="form-control" required data-validation-required-message="{{ __('admin.this_field_is_required') }}">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4 col-12">
                                                <div class="form-group">
                                                    <label for="first-name-column">{{  __('admin.new_password_confirm') }}</label>
                                                    <div class="controls">
                                                        <input type="password" name="password_confirmation" class="form-control" required data-validation-required-message="{{ __('admin.this_field_is_required') }}">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    
                                        <div class="col-12 d-flex justify-content-center mt-3">
                                          <button type="submit" class="btn btn-primary mr-1 mb-1 submit_button">{{__('admin.saving_changes')}}</button>
                                          <a href="{{ url()->previous() }}" type="reset" class="btn btn-outline-warning mr-1 mb-1">{{__('admin.back')}}</a>
                                      </div>
                                    </div>
                                </form>
                              </div>

                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!-- account setting page end -->

</div>

@endsection
@section('js')
    <script src="{{asset('admin/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js')}}"></script>
    <script src="{{asset('admin/app-assets/js/scripts/forms/validation/form-validation.js')}}"></script>
  {{-- show selected image script --}}
    @include('admin.shared.addImage')
  {{-- show selected image script --}}
@endsection